name: test_task
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  salomon_bottom_bar: ^3.3.2
  go_router: ^11.1.2
  auth: ^8.2.0+02
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6


flutter:
  uses-material-design: true
